---
title: Me learning Github
date: 2019-05-28
---
title: Me learning Github
author: Devin Wilkins
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Woot. Using Github is awesome.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme:jekyll-theme-minimal
